version: '3.8'

services:
  # PostgreSQL Database for Keycloak
  keycloak-db:
    image: postgres:15-alpine
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - auth-network
    ports:
      - "5433:5432"  # Exposed for debugging, different port to avoid conflicts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Keycloak Authorization Server
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    container_name: keycloak-server
    environment:
      # Database configuration
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_password
      
      # Keycloak admin user
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_password
      
      # Keycloak configuration
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      
      # Performance and production settings
      KC_CACHE_STACK: kubernetes
      KC_PROXY: edge
      
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
      - ./keycloak/themes:/opt/keycloak/themes
    ports:
      - "8080:8080"
    depends_on:
      keycloak-db:
        condition: service_healthy
    networks:
      - auth-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/realms/master || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s

  # PostgreSQL Database for Application (optional - you can use H2 for development)
  app-db:
    image: postgres:15-alpine
    container_name: app-postgres
    environment:
      POSTGRES_DB: authapp
      POSTGRES_USER: authapp
      POSTGRES_PASSWORD: app_password
    volumes:
      - app_db_data:/var/lib/postgresql/data
    networks:
      - auth-network
    ports:
      - "5434:5432"  # Exposed for debugging
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U authapp"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  keycloak_db_data:
    driver: local
  app_db_data:
    driver: local

networks:
  auth-network:
    driver: bridge
