#!/bin/bash

# This script helps configure Keycloak client secret
echo "🔧 Keycloak Configuration Helper"
echo ""
echo "After starting Keycloak, you need to:"
echo ""
echo "1. 🌐 Go to: http://localhost:8080"
echo "2. 🔑 Login with: admin / admin_password"
echo "3. 🏢 Select realm: auth-demo-realm"
echo "4. 🔧 Go to: Clients → auth-demo-client"
echo "5. 📋 Go to: Credentials tab"
echo "6. 📝 Copy the Client Secret"
echo "7. ✏️  Update src/main/resources/application.properties:"
echo "   spring.security.oauth2.client.registration.keycloak.client-secret=YOUR_CLIENT_SECRET"
echo ""
echo "🧪 Test with curl:"
echo ""
echo "# Get token:"
echo "TOKEN=\$(curl -s -X POST http://localhost:8080/realms/auth-demo-realm/protocol/openid-connect/token \\"
echo "  -H \"Content-Type: application/x-www-form-urlencoded\" \\"
echo "  -d \"grant_type=password&client_id=auth-demo-client&username=user&password=user123\" \\"
echo "  | jq -r '.access_token')"
echo ""
echo "# Use token:"
echo "curl -H \"Authorization: Bearer \$TOKEN\" http://localhost:8081/api/user/profile"
echo ""
echo "🔐 Available test users:"
echo "- admin/admin123 (ADMIN role)"
echo "- manager/manager123 (MANAGER role)" 
echo "- user/user123 (USER role)"
echo "- guest/guest123 (GUEST role)"
